-- DDL generated by Postico 2.1.2
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE flavors (
    id character varying(25),
    name character varying(25),
    is_favorite character varying(25),
    created_at character varying(25),
    updated_at character varying(25)
);

